# Use Node image as base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the remaining application files
COPY . .

# Build the Angular application
RUN npm run build

# Set the default command to run when the container starts
CMD [ "npm", "start" ]
